version: '3'
services:

  mongodb:
    networks:
        - dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./data/db:/data/db
    restart: always
    user: mongodb
    ports: ["27017:27017"]
    image: 'rhelling/alpine-mongodb'
networks:
    dev: 
        driver: bridge
